name: build

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: docker-compose up -d

      - name: wait mysql ready
        run: bash ./wait_mysql_ready.sh

      - run: docker-compose logs
        if: "${{ failure() }}"

      - run: cp ./wait_mysql_ready.sh dist

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - run: yarn

      - run: mysqldump -h 127.0.0.1 -u root -psecret --databases bangumi --column-statistics=0 --skip-dump-date --no-data > ./dump-schema.sql
      - run: npx prettier --expression-width 50 -w ./dump-schema.sql

      - run: mysqldump -h 127.0.0.1 -u root -psecret --databases bangumi --column-statistics=0 --skip-dump-date --hex-blob --no-create-info > ./dump-data.sql
      - run: npx prettier --expression-width 1000 -w ./dump-data.sql

      - run: cat ./dump-schema.sql ./dump-data.sql > ./dist/dist.sql

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist/
          commit_message: deploy ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
